---
title: "Non centered Factor Stochastic Volatility"
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(ggmcmc)
library(coda)
library(latex2exp)
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
theme_set(theme_minimal())
source("mcmc_summarise.R")
```

## Factor Stochastic Volatility with Dynamic Mean

Factor Stochastic volatility models typically model centered data. Combining the DLM with the FSV model allows us to model multivariate non-centered time series.

```{r dlm-fsv-sims}
sims = read_csv("~/git/bayesian_dlms/examples/data/dlm_fsv_system_sims.csv")

p1 = sims %>%
    filter(time < 500) %>%
    ggplot(aes(x = time, y = observation)) +
    geom_line() +
    theme(legend.position = "none") +
    labs(title = "Observations")

p2 = sims %>%
    filter(time < 500) %>%
    select(time, contains("log")) %>%
    gather(key, value, -time) %>%
    ggplot(aes(x = time, y = value, colour = key)) +
    geom_line() +
    theme(legend.position = "none") +
    facet_wrap(~key, ncol = 1)

p1 / p2
```

```{r dlm-fsv-params}
# TODO: Parameter diagnostics of DLM FSV System model
files = c("~/git/bayesian_dlms/examples/data/dlm_fsv_system_params_0.csv",
          "~/git/bayesian_dlms/examples/data/dlm_fsv_system_params_1.csv")

param_names = c("v", paste0("w", 1:13), paste0("m0", 1:13), paste0("c0", 1:13), paste0("sigma_x", 1:13), paste0("beta", 1:26),
                paste(rep(c("phi", "mu", "sigma_eta"), 2),
                      c(rep(1, 3), rep(2, 3)), sep = "_"))

beta_mat = matrix(c(1.0, 0.0, 4.94, 1.0, 3.38, 2.74, 5.00, 0.95, -4.57, -7.4, -0.12, 8.2, 1.35, -2.8, -10.61, -2.2, -1.39, -0.75, 2.15, 0.31, -1.16, 1.46, 2.07, 2.18, 12.52, -4.0), ncol = 2, byrow = T)

actual_values = data_frame(
    Parameter = param_names,
    actual_value = c(0.5, rep(1.0, 13), rep(0.0, 13), rep(1.0, 13),
                  rep(0.1, 13), as.vector(beta_mat), rep(c(0.8, 0.0, 0.2), 2)))

chains = read_chains(files, nth = 1, drop = 0, param_names = param_names)

chains %>%
    group_by(Parameter) %>%
    summarise(mean(value)) %>%
    inner_join(actual_values)  %>%
    print(n = Inf)
```


```{r beta-dlm-fsv}
# Beta summary
chains %>%
    filter(grepl(x = Parameter, pattern = "*beta*")) %>%
    filter(!(Parameter %in% c("beta1", "beta14", "beta15"))) %>%
    traceplot()
```

```{r log-volatility-dlm-fsv}
# log-volatility parameters
chains %>%
    filter(grepl(x = Parameter, pattern = "*mu*|*sigma_eta*|*phi*")) %>%
    filter(Parameter != "sigma_x") %>%
    traceplot()
```