---
title: "Particle Marginal Metropolis Hastings"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
```

The Particle Marginal Metropolis Hastings (PMMH) algorithm can be used to learn parameters of a Dynamic Generalised Linear Model (DGLM).

The algorithm uses an unbiased estimate of the marginal likelihood, $p(y_{1:T} | x_{0:T}, V, W)$ in a [Metropolis-Hastings Algorithm](https://en.wikipedia.org/wiki/Metropolis–Hastings_algorithm). The pseudo marginal likelihood can be calculated using the Particle Filter.

Firstly define a DGLM:

```tut
import dlm.model._

val model = Dlm.polynomial(1)
val dglm = Dglm.poisson(model)
```

Assume we have some observations of a process which can be modelled using the specified model:

```scala
val observations = // some observations
```

Then we need to define the proposal function, `def proposal: Parameters => Rand[Parameters]`. A symmetric proposal distribution is implemented in the `Metropolis` object. This proposal distribution is simply a Normal centered at the previous value of the parameters. In the case of the non-negative parameters, $V$, $W$ and $C_0$ the parameter is multiplied by the exponential of a Normal random number.

The function accepts a parameter `delta`, a single `Double` value which controls the variance of the Gaussian proposal distribution:

```tut
def proposal = Metropolis.symmetricProposal(0.05) _
```

Then we need to specify a prior distribution for the parameters, which encapsulates our prior beliefs about the parameters.

```scala
def prior(p: Dlm.Parameters): Double = ???
```

Then we must specify the initial value of the parameters to start the MCMC, this can be a sample from the prior distribution. The PMMH algorithm is available to use in the Bayesian DLM Scala library, using the bootstrap particle filter to estimate the likelihood:

```scala
val iters = MetropolisHastings.pmmh(
  dglm, 
  observations,
  proposal,
  prior,
  initP
  n = 500)
```

With this specification, there are two tuning parameters in the PMMH algorithm, the variance of the Gaussian proposal distribution and the number of particles in the Particle Filter. As the number of particles increases so does the accuracy of the likelihood estimate, however this also increases computational time. The variance of the proposal distribution should be such that the proportion of accepted moves in the pmmh algorithm is approximately one third. This will guarantee that the MCMC has explored the full parameter posterior.