---
title: "Regression DLM"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(coda)
library(ggmcmc)
library(patchwork)
library(latex2exp)

theme_set(theme_minimal())
```

# Simulation

```{r}
data = read_csv("../examples/data/multivariate_regression_sims.csv")

p1 = data %>%
  gather(key = "observation", value, contains("observation")) %>%
  ggplot(aes(x = time, y = value, colour = observation)) +
  geom_line() +
  theme(legend.position = "bottom") +
  labs(title = "Simulated values from the Regression DLM")

p2 = data %>%
  gather(key = "observation", value, contains("covariate")) %>%
  ggplot(aes(x = time, y = value, colour = observation)) +
  geom_line() +
  theme(legend.position = "bottom") +
  labs(title = "Covariates of the Regression DLM")

p1 / p2
```

```{r}
actual_values = tibble(
  Parameter = c("W", "V"),
  actual_value = c(3.0, 2.0)
)
```

```{r first-order-gibbs}
params = c(paste0("V", 1:4), paste0("W", 1:8))
iters = read_csv("../examples/data/multivariate_regression_gibbs_0.csv", col_names = params)
iters2 = read_csv("../examples/data/multivariate_regression_gibbs_1.csv", col_names = params)
chain = ggs(mcmc.list(mcmc(iters[seq(1, nrow(iters), by = 10),]), mcmc(iters2[seq(1, nrow(iters2), by = 10),])))

ggs_traceplot(chain) + facet_wrap(~Parameter, strip.position = "right")

ggs_autocorrelation(chain)

ggs_density(chain) +
```

