---
title: "DLM with Time Varying Measurement Noise"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(coda)
library(ggmcmc)
library(patchwork)
library(latex2exp)

theme_set(theme_minimal())
```

# Simulation

$$\begin{align}
	Y_t &= \sigma \exp\left\{ \frac{alpha_t}{2} \right\}, \quad \sigma \sim \mathcal{N}(0, 1), \\
	\alpha_t &= \phi \alpha_{t-1} + \eta, \quad \eta \sim \mathcal{N}(0, \sigma_\eta), \\
	\alpha_0 \sim \mathcal{N}(0, \sigma^2/(1-\phi^2)).
\end{align}$$

```tut:silent
import core.dlm.model._
import breeze.linalg.{DenseMatrix, DenseVector, diag}

val mod = Dlm.polynomial(1)
val p = Dlm.Parameters(
  v = DenseMatrix(2.0),
  w = DenseMatrix(3.0),
  m0 = DenseVector(0.0),
  c0 = DenseMatrix(1.0)
)

val data = StochasticVolatility.simulate(0, mod, p, 1.0).
  steps.
  take(1000).
  toVector
```

The figure below shows a plot of 100 simulations from a first order DLM with a time varying variance.

```{r stochastic-volatility-simulated}
data = read_csv("../core/data/sv_sims.csv")

data %>%
  gather(key, value, -time) %>%
  ggplot(aes(x = time, y = value, colour = key)) +
  geom_line() +
  theme(legend.position = "bottom") +
    labs(title = "Simulated values from the first order DLM with Dynamic Variance",
         subtitle = TeX("$\\phi = 0.8$, $\\sigma = 0.2$")) +
    facet_wrap(~key, ncol = 1, scales = "free_y")
```

```{r stochastic-volatility-parameters}
iters = read_csv("../core/data/sv_params.csv")

burn = 1e4
thin = 20
params = ggs(mcmc(iters[seq(burn, to = nrow(iters), by = thin),-2]))

p1 = params %>%
  ggplot(aes(x = Iteration, y = value)) +
  geom_line() +
  facet_wrap(~Parameter, scales = "free_y")

p2 = params %>% 
  ggs_autocorrelation()

p3 = ggs_density(params) + facet_wrap(~Parameter, ncol = 2)

p1 / p2 / p3
```

## Heteroskedastic First Order DLM 

```{r dlm-sv-plot}
sims = read_csv("../core/data/first_order_dlm_var.csv")

sims %>%
  gather(key, value, -time) %>%
  ggplot(aes(x = time, y = value, colour = key)) +
  geom_line() +
  theme(legend.position = "bottom") +
    labs(title = "Simulated values from the first order DLM with Dynamic Variance",
         subtitle = TeX("$W = 3$, $\\phi = 0.8$, $\\sigma = 0.2$")) +
    facet_wrap(~key, ncol = 1, scales = "free_y")
```

```{r dlm-sv-parameters}
iters = read_csv("../core/data/first_order_dlm_var_params.csv")

burn = 1e3
thin = 2
params = ggs(mcmc(iters[seq(burn, to = nrow(iters), by = thin),]))

p1 = params %>%
  ggplot(aes(x = Iteration, y = value)) +
  geom_line() +
  facet_wrap(~Parameter, scales = "free_y")

p2 = params %>% 
  ggs_autocorrelation()

p3 = ggs_density(params) + facet_wrap(~Parameter, ncol = 3)

p1 / p2 / p3
```

```{r}

```
